# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python application

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Lint with flake8
      run: |
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
    - uses: actions/upload-artifact@v2
      with:
        name: artifact
        if-no-files-found: error # 'warn' or 'ignore' are also available, defaults to `warn` 
        path: ${{ github.workspace }}
        retention-days: 1
  security:
    needs: build
    runs-on: ubuntu-latest
    env:
      OWASP_DEPCHECK: KMUkV0WjQ1SERyYGMeKJtQ
      SONARQUBE: P8qxCsJxQim4eN5E5e8vMg
    steps:
    - uses: actions/download-artifact@v2
      with:
        name: artifact
    - name: loop security
      env:       
        LIST: KMUkV0WjQ1SERyYGMeKJtQ P8qxCsJxQim4eN5E5e8vMg
      run: for f in $LIST; do docker run -e POLICY_ID=$f -v $GITHUB_WORKSPACE:/code -v $GITHUB_WORKSPACE:/results -v /var/run/docker.sock:/var/run/docker.sock -e SONAR_JAVA_LIBRARY_DIR=\".\" -e SONAR_JAVA_BINARY_DIR=\".\" -e CYBRIC_API_KEY=${{ secrets.ZN_API_KEY }} zeronorth/integration:latest python cybric.py; done
  
      

